package nl.gogognome.gogoaccount.component.invoice;

import nl.gogognome.dataaccess.dao.AbstractDomainClassDAO;
import nl.gogognome.dataaccess.dao.NameValuePairs;
import nl.gogognome.dataaccess.dao.ResultSetWrapper;
import nl.gogognome.gogoaccount.component.document.Document;
import nl.gogognome.lib.text.AmountFormat;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;

class PaymentDAO extends AbstractDomainClassDAO<Payment> {

    private final Document document;

    public PaymentDAO(Document document) {
        super("payment", "domain_class_sequence", document.getBookkeepingId());
        this.document = document;
    }

    public List<Payment> findForInvoice(String invoiceId) throws SQLException {
        return findAll(new NameValuePairs().add("invoice_id", invoiceId), "date");
    }

    @Override
    protected Payment getObjectFromResultSet(ResultSetWrapper result) throws SQLException {
        Payment payment = new Payment(result.getString("id"));
        payment.setInvoiceId(result.getString("invoice_id"));
        payment.setDescription(result.getString("description"));
        payment.setDate(result.getDate("date"));
        try {
            AmountFormat amountFormat = new AmountFormat(document.getLocale());
            payment.setAmount(amountFormat.parse(result.getString("amount")));
        } catch (ParseException e) {
            throw new SQLException("Could not parse amount " + result.getString("amount"));
        }
        return payment;
    }

    public boolean hasPayments(String invoiceId) throws SQLException {
        return existsAtLeastOne(new NameValuePairs().add("invoice_id", invoiceId));
    }

    @Override
    protected NameValuePairs getNameValuePairs(Payment payment) throws SQLException {
        return new NameValuePairs()
                .add("id", payment.getId())
                .add("invoice_id", payment.getInvoiceId())
                .add("description", payment.getDescription())
                .add("date", payment.getDate())
                .add("amount", new AmountFormat(document.getLocale()).formatAmount(payment.getAmount()));
    }

    @Override
    protected void addAutoGeneratedValues(NameValuePairs nameValuePairs, Payment object) throws SQLException {
        // Preserve id if it is already present
        if (nameValuePairs.getValue("id") == null) {
            nameValuePairs.remove("id"); // needed in case name id is present with value null.
            nameValuePairs.add("id", Long.toString(this.getNextLongFromSequence(this.sequenceName)));
        }
    }
}
