package nl.gogognome.gogoaccount.test;

import nl.gogognome.gogoaccount.component.configuration.ConfigurationService;
import nl.gogognome.gogoaccount.component.invoice.Invoice;
import nl.gogognome.gogoaccount.component.invoice.InvoiceLineDefinition;
import nl.gogognome.gogoaccount.component.invoice.InvoiceSearchCriteria;
import nl.gogognome.gogoaccount.component.invoice.InvoiceService;
import nl.gogognome.gogoaccount.component.party.Party;
import nl.gogognome.gogoaccount.component.party.PartyService;
import nl.gogognome.gogoaccount.services.ServiceException;
import nl.gogognome.gogoaccount.util.ObjectFactory;
import nl.gogognome.lib.text.Amount;
import nl.gogognome.lib.util.DateUtil;
import org.junit.Test;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import static junit.framework.Assert.assertEquals;

public class TestInvoiceService extends AbstractBookkeepingTest {

    private final ConfigurationService configurationService = new ConfigurationService();
    private final InvoiceService invoiceService = ObjectFactory.create(InvoiceService.class);
    private final PartyService partyService = new PartyService();

    @Test
    public void testInvoiceCreation() throws Exception {
        List<Party> parties = partyService.findAllParties(document);
        Date issueDate = DateUtil.createDate(2011, 8, 20);
        Amount amount = createAmount(20);
        List<InvoiceLineDefinition> lines = Arrays.asList(
            new InvoiceLineDefinition(amount, null, configurationService.getAccount(document, "190"), true),
            new InvoiceLineDefinition(null, amount, configurationService.getAccount(document, "400"), false));
        invoiceService.createInvoiceAndJournalForParties(document, "inv-{id}", parties, issueDate, "Invoice for {name}", lines);

        for (Party party : parties) {
            Invoice invoice = invoiceService.getInvoice(document, "inv-" + party.getId());
            assertEquals("[Invoice for " + party.getName() + ", Zaalhuur]", invoiceService.findDescriptions(document, invoice).toString());
            assertEquals(amount, invoice.getAmountToBePaid());
        }
    }

    @Test
    public void testInvoiceCreationWithAutoGeneratedIds() throws Exception {
        List<Party> parties = partyService.findAllParties(document);
        Date issueDate = DateUtil.createDate(2011, 8, 20);
        Amount a = createAmount(20);
        List<InvoiceLineDefinition> lines = Arrays.asList(
            new InvoiceLineDefinition(a, null, configurationService.getAccount(document, "190"), true),
            new InvoiceLineDefinition(null, a, configurationService.getAccount(document, "400"), false));
        invoiceService.createInvoiceAndJournalForParties(document, "auto", parties, issueDate, "Invoice for {name}", lines);

        for (Party p : parties) {
            InvoiceSearchCriteria searchCriteria = new InvoiceSearchCriteria();
            searchCriteria.setName(p.getName());
            searchCriteria.setId("auto");
            List<Invoice> invoices = invoiceService.findInvoices(document, searchCriteria);
            assertEquals(1, invoices.size());

            Invoice inv = invoices.get(0);
            assertEquals("[Invoice for " + p.getName() + ", Zaalhuur]", invoiceService.findDescriptions(document, inv).toString());
            assertEquals(a, inv.getAmountToBePaid());
        }
    }

    @Test(expected = ServiceException.class)
    public void cannotCreateInvoicesWithoutAmountToBePaidSelected() throws Exception {
        List<Party> parties = partyService.findAllParties(document);
        Date issueDate = DateUtil.createDate(2011, 8, 20);
        Amount a = createAmount(20);
        List<InvoiceLineDefinition> lines = Arrays.asList(
            new InvoiceLineDefinition(a, null, configurationService.getAccount(document, "190"), false),
            new InvoiceLineDefinition(null, a, configurationService.getAccount(document, "400"), false));

        invoiceService.createInvoiceAndJournalForParties(document, "inv-{id}", parties, issueDate, "Invoice for {name}", lines);
    }

    @Test(expected = ServiceException.class)
    public void cannotCreateInvoicesWithMultipleAmountToBePaidSelected() throws Exception {
        List<Party> parties = partyService.findAllParties(document);
        Date issueDate = DateUtil.createDate(2011, 8, 20);
        Amount a = createAmount(20);
        List<InvoiceLineDefinition> lines = Arrays.asList(
            new InvoiceLineDefinition(a, null, configurationService.getAccount(document, "190"), true),
            new InvoiceLineDefinition(null, a, configurationService.getAccount(document, "400"), true));

        invoiceService.createInvoiceAndJournalForParties(document, "inv-{id}", parties, issueDate, "Invoice for {name}", lines);
    }

    @Test(expected = ServiceException.class)
    public void cannotCreateInvoicesWithoutDebetOrCreditAmountOnSingleLine() throws Exception {
        List<Party> parties = partyService.findAllParties(document);
        Date issueDate = DateUtil.createDate(2011, 8, 20);
        Amount a = createAmount(20);
        List<InvoiceLineDefinition> lines = Arrays.asList(
            new InvoiceLineDefinition(a, null, configurationService.getAccount(document, "190"), true),
            new InvoiceLineDefinition(null, null, configurationService.getAccount(document, "190"), false),
            new InvoiceLineDefinition(null, a, configurationService.getAccount(document, "400"), false));

        invoiceService.createInvoiceAndJournalForParties(document, "inv-{id}", parties, issueDate, "Invoice for {name}", lines);
    }

    @Test(expected = ServiceException.class)
    public void cannotCreateInvoicesWithDebetAndCreditAmountOnSingleLine() throws Exception {
        List<Party> parties = partyService.findAllParties(document);
        Date issueDate = DateUtil.createDate(2011, 8, 20);
        Amount a = createAmount(20);
        List<InvoiceLineDefinition> lines = Arrays.asList(
            new InvoiceLineDefinition(a, null, configurationService.getAccount(document, "190"), true),
            new InvoiceLineDefinition(a, a, configurationService.getAccount(document, "190"), false),
            new InvoiceLineDefinition(null, a, configurationService.getAccount(document, "400"), false));

        invoiceService.createInvoiceAndJournalForParties(document, "inv-{id}", parties, issueDate, "Invoice for {name}", lines);
    }

    @Test
    public void updateExistingInvoice() throws Exception {
        List<String> descriptions = Arrays.asList("Sponsoring 2011", "Sponsoring");
        List<Amount> amounts = Arrays.asList(null, createAmount(30));
        Party party = partyService.getParty(document, "1102");
        Invoice invoice = new Invoice("inv1");
        invoice.setConcerningPartyId(party.getId());
        invoice.setPayingPartyId(party.getId());
        invoice.setAmountToBePaid(createAmount(30));
        invoice.setIssueDate(DateUtil.createDate(2011, 5, 6));

        invoiceService.updateInvoice(document, invoice, descriptions, amounts);

        assertEqualInvoice(invoice, invoiceService.getInvoice(document, "inv1"));
        assertEquals(descriptions, invoiceService.findDescriptions(document, invoice));
        assertEquals(amounts, invoiceService.findAmounts(document, invoice));
    }

    @Test(expected = ServiceException.class)
    public void updateNonExistingInvoiceFails() throws Exception {
        List<String> descriptions = Arrays.asList("Sponsoring 2011", "Sponsoring");
        List<Amount> amounts = Arrays.asList(null, createAmount(30));
        Party party = partyService.getParty(document, "1102");
        Invoice invoice = new Invoice("inv421");
        invoice.setConcerningPartyId(party.getId());
        invoice.setPayingPartyId(party.getId());
        invoice.setAmountToBePaid(createAmount(30));
        invoice.setIssueDate(DateUtil.createDate(2011, 5, 6));

        invoiceService.updateInvoice(document, invoice, descriptions, amounts);
    }
}
